-- Update users table with new fields
ALTER TABLE users
ADD COLUMN email VARCHAR(255) UNIQUE NOT NULL,
ADD COLUMN phone_number VARCHAR(20),
ADD COLUMN is_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN verification_token VARCHAR(255),
ADD COLUMN reset_token VARCHAR(255),
ADD COLUMN reset_token_expires DATETIME,
ADD COLUMN last_login DATETIME,
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
